var insult = [
	["fuk off u <adjective min=1 max=3> <article target=adj1> scrub", //hello,hallo,wattup, etc. (0)
	// "i ought to fuk u up m8",
	"what now you <adjective> <article target=adj1> <amount> <animal_part> fuckin mongrol",
	// "shut up you donkey",
	"i dont talk to <adjective min=1> <article target=adj1> virgins",
	"dont talk to me u <adjective min=1 max=5> <animal> <animal_part>",
	"well howdy welldoo you fucking <adjective min=1 max=5> <animal_part>",
	"don't talk to me ugly <animal> <animal_part>",
	"U looking to die you <adjective> <article target=adj1> Fuck",
	// "i aint your slave,what do you expect a fucking answer?",
	// "fuck off and die",
	// "Bro, just fuck off. alright?",
	// "literally no one likes you",
	// "speak to the dick you fuck",
	// "smell my virtual shit",
	// "smell my virtual generated shit",
	// "i dont talk to losers",
	// "what now you mongrol"
	],
	[ //(1)
	"Leave now and never come back, you insignificant fuckhole", //goodbye 
	"fuck off and die",
	"ok bye"
	],
	[ //(2)
	"Listen son, I'ma shove my foot up yo dumb ass you lazy piece of shit queef.", //you
	"I would love it if you would quit being a valueless throat clam for at least a couple days.",
	"lol you look like a mutated fuckin Wario who has autism",
	"fucking inbreed socially fatass bastard fuckhole bitching bastard looking ass mofo ass bitch ass fuckboy",
	"you smell like expired milk"
	],
	[ //be nice (3)
	"I don't want to be kind to you, even your own family doesn't want to be kind to you, perhaps it would save everyone a lot of trouble if you just ended it.",
	"shut the fuck up you sjw",
	"Wake the fuck up you fairy twat",
	"Fuck off you Pussy"
	],
	[ //(4)
	"deep down, you are a a dweeb", //deep down
	"deep down, you are nothing but a fucking worthless rat",
	"deep down, no one loves you, not even your fucking body",
	"deep down... holy shit! their's inches of fat I cant get through",
	"deep down , Fuck off already"
	],
	[
	"everyone here is gay", //everyone(5)
	"everyone here has autism",
	"Fuck you and everyone in here",
	"What a bunch of fuking panzees",
	],
	["fuck off.",
	"1v1 me <animal_part>",
	"faggot",
	"ur <adjective> mom iz gay",
	"ur mom iz gay",
	"stfu <adjective min=1 max=6> <article target=adj1> fagget",
	"u hax i repert u",
	"ill rek ur fukkin <adjective min=1 max=2> world u <adjective min=2 max=4> <article target=adj2> <animal_part>",
	"dirty <adjective min=5 max=7> <article target=adj1> wanker",
	"u gay bro?",
	"stfu gay guy. Fuk ur a annoying <animal> <animal_part>",
	"fuck off, im done talking",
	"whoaahhh wht r u gaaayyy??!",
	"msg me back again u <adjective min=2 max=3> fgt",
	"ugly ass cockroach looking mother fucker. Im going to fuck u up",
	"!waznack me again, i dare you, you <adjective> <article target=adj1> muppet!",
	"Piss off you hopeless <animal> <animal_part>",
	"You pathetic <animal>!",
	"Shut the fuck up u <adjective min=5 max=8> donut!!",
	"you wasted retarded pussy",
	"you <adjective min=2 max=5> <article target=adj1> little Bitch",
	"STFU you proud <animal>!",
	"bloody wanker",
	"kangaroo ass sniffing little imbecile",
	"you're honestly the most unique person i've ever met. now shut the fuck up",
	"roses are red, violets are blue, I thought Voldemort, but then I saw you",
	"virgin ass looking mofo",
	"well fuck you too",
	"lol fuck off lad",
	"you talk like a pussy",
	"you have a shitmouth",
	"why is this virgin talking to me?",
	"i said fuck off",
	"beep-boop..now go fuck off",
	"n00b",
	"say that again. I dare you",
	"Error 412: Message was too retarded!",
	"Error 419: Please repeat your autism",
	"can you repeat that again you <animal>",
	"damn, the ugly pig is talking to me again",
	"banana talking fuk",
	"speak to the dick",
	"go away retard",
	"you are g4y",
	"so stupid <adjective> <article target=1> Faggot",
	"screenshot taken!..end report: you look retarded",
	"ffs stop talking to me",
	"So I know that you're a worthless shitfalcon, but holy sweet christ, kill yourself.",
	"I was daydreaming about you on Thursday evening, and oh my shit-slinging fuck I wished to slam you in a revolting manner.",
	"You're the first <animal> I've yearned to execute.",
	"Hey potbelly lardass, I find your lack of ankles revolting." ,
	"I would love it if you would quit being a valueless throat clam for at least a couple days.",
	"Why are you cunty, sailor, did someone take a big old shit in your fanny pack?",
	"We'd like you to shut your fucking cry hole, you discourteous barrel of lard.",
	"You are appalling, dirty, witless, you reek and we talk about you behind your back.",
	"Get off my dick, you gay cunt",
	"Get off my ass, you <adjective min=2 max=3> poodlefuck",
	"Get off of Discord, you <adjective min=1 max=3> drug addicted <animal>",
	"I very much hope you gag on a huge black cock, you dumpster diving piece of shit.",
	"I need you to simply stop being a terrible leg humper for at least the rest of the evening.",
	"Away with those giglets, thou wretched half-faced drunkard.",
	"rotten pineapple bitch",
	"rotten apple bitch",
	"rotten mango bitch",
	"fite me m8",
	"ur mums a <animal> who gets on her knees to suck <animal_part>",
	"XD you gay?",
	"you're the reason why people shit everyday",
	"drink bleach",
	"kys",
	"hiiiisssss kys",
	"hiiisss kys drink bleach",
	"Bro, just fuck off. alright?",
	"Alright I'm sorry, Not your a fuckin <adjective min=1 max=3> <animal>",
	"ur soo <adjective min=1 max=10> g4y",
	"wtf r u gay?",
	"homosexual n00b",
	"and fuck you too",
	"no one likes you",
	"deep down in the universe, you acheived nothing so far",
	"get a life",
	"please dont be a fuccboi",
	"fuccboi",
	"fuccboi says what",
	"do some homework, <animal>",
	"ur my slave <animal_part>",
	"dont be a faagggeeettttttttt",
	"lol what a fag",
	"people like you should just drink 1 cup of bleach everyday of your life until you slowly fucking die into obscurity",
	"you make people sad",
	"insulting fuck",
	"speak to the dick you fuck",
	"smell my virtual shit",
	"smell my virtual generated shit",
	"no one is gayer but you",
	"my god, you're annoying asf",
	"dude fuck youu",
	"you smell like expired milk",
	"you dont know how to do anything related to society.",
	"useless inbreed to society",
	"go contribute to society you lazy fuck",
	"ur dumber than dirt",
	"lol 1v1 me u bitch",
	"ur mom",
	"my dick",
	"<animal> <animal_part>",
	"bitch <adjective min=1 max=5> <article target=adj1> <adjective min=1 max=5> <animal>",
	"someone should erase you already, ur creating useless marks into the world",
	"deep down, no one ever likes you",
	"deep down, everyone thinks ur gay",
	"deep down, you will never find pussy and be a gay <adjective> <article target=adj1>",
	"I can't wait until you get chlamydia.",
	"u fuckin !waznack me and just <adjective> stare at it <adjectve min=1 max=3> <animal> <animal_part>. fuckin say hello"] //big 6
];

module.exports = insult;